# Generated by Django 4.1.6 on 2023-03-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicio1', '0002_pasos_ingrediente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pasos',
            new_name='Paso',
        ),
    ]
