# Generated by Django 4.1.6 on 2023-03-16 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicio1', '0003_rename_pasos_paso'),
    ]

    operations = [
        migrations.AddField(
            model_name='paso',
            name='descripcion',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
